### ISSUE TITLE
NTFS and exFAT MBR partitions are shown as "IFS"

### ISSUE THREAD

**Issue by marcosfrm** [tenox7/lsblk#7]
MBR partition type `0x07` nowadays is used for NTFS and exFAT. IFS is an interface OS/2 used to expose to filesystem drivers I think. Linux's ~libblkid~ libfdisk is a good source for this kind of stuff:

https://github.com/util-linux/util-linux/blob/v2.39.3/include/pt-mbr-partnames.h#L12

By the way, here is the GPT partition list:

https://github.com/util-linux/util-linux/blob/v2.39.3/include/pt-gpt-partnames.h

**Comment by tenox7** [comment]
awe thank you, perhaps you could send a PR? I don't do much Win32 development these days

**Comment by marcosfrm** [comment]
Hmm, MBR partition description is somewhat confusing:

```
Primary NTFS/exFAT NTFS H:
Primary NTFS/exFAT exFAT J:
```
(and ReFS is also 0x07...)

Would not be cleaner show the hex code instead?

```
Primary type 0x07 NTFS H:
```
